spring.application.name=auth-service

#Database configs used postgres
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Supabase disconnect issue fix
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.connection-timeout=20000

#Devtools
spring.devtools.restart.enabled=true

server.port=${PORT:8081}

jwt.secret=tempDevSecretKeyForJwtSigning123456789ABCDEF
jwt.expiration=86400000

#Oauth configs
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

#Send grid configs
brevo.api.key=${BREVO_API_KEY}
brevo.from.email=${BREVO_FROM_EMAIL}
brevo.from.name=${BREVO_FROM_NAME}

#frontend url
app.frontend-url=${FRONTEND_URL}
#Backend url
app.backend-url=${APP_BACKEND_URL:http://localhost:8081}